application: onepointstaging
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

handlers:

- url: /_ah/warmup
  script: warmup_requests.app
  secure: always

######################### REST ENDPOINTS #########################

- url: /rest/appliance/.*
  script: handlers.rest.appliance.app

- url: /rest/provider/.*
  script: handlers.rest.provider.app

######################### STATIC ENDPOINTS #########################

- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/scss
  static_dir: assets/scss

- url: /assets
  static_dir: assets

- url: /favicon\.ico
  mime_type: image/png
  static_files: assets/img/favicon.png
  upload: assets/img/favicon\.png

######################### WEB ENDPOINTS #########################
- url: /rest/fb_login
  script: handlers.rest.login.app
  secure: never

- url: /rest/logout
  script: handlers.rest.login.app
  secure: never

- url: /rest/temp_login
  script: handlers.rest.login.app
  secure: never

- url: /rest/create/.*
  script: handlers.rest.data_create.app
  secure: never

- url: /rest/work_order/.*
  script: handlers.rest.work_order.app
  secure: never

- url: /data_creation/.*
  script: handlers.web.data_creation.app
  secure: never

- url: /appliance/.*
  script: handlers.web.appliance.app
  secure: never

- url: /provider/.*
  script: handlers.web.provider.app
  secure: never

- url: /work_order/.*
  script: handlers.web.work_order.app
  secure: never

- url: /.*
  script: handlers.web.index.app
  secure: never

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
