application: onepointapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

handlers:

- url: /_ah/warmup
  script: warmup_requests.app
  secure: always

######################### REST ENDPOINTS #########################

######################### STATIC ENDPOINTS #########################

######################### WEB ENDPOINTS #########################

- url: /.*
  script: handlers.web.app
  secure: never

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
